# API Urls
API_URI='https://api.ttlock.com/v3'
USER_API_URI = 'https://api.ttlock.com/v3/user/?'
LOCK_API_URI = 'https://api.ttlock.com/v3/lock/?'
EKEY_API_URI = 'https://api.ttlock.com/v3/key/'
PASSCODE_API_URI = 'https://api.ttlock.com/v3/keyboardPwd/?'
GATEWAY_API_URI = 'https://api.ttlock.com/v3/gateway/?'
ICCARD_API_URI = 'https://api.ttlock.com/v3/identityCard/?'
FINGERPRINT_API_URI = 'https://api.ttlock.com/v3/fingerprint/?'
UNLOCK_RECORD_API_URI = 'https://api.ttlock.com/v3/lockRecord/?'
WIRELESS_KEYBOARD_API_URI = 'https://api.ttlock.com/v3/wirelessKeypad/'

# FIELDS
ERROR_CODE_FIELD = 'errcode'
MENSSAGE_FIELD = 'errmsg'
LIST_FIELD = 'list'
STATE_FIELD = 'state'
PAGES_FIELD = 'pages'
GATEWAY_MAC_FIELD = 'gatewayMac'
LOCK_MAC_FIELD ='lockMac'
LOCK_ALIAS_FIELD = 'lockAlias'
LOCK_ID_FIELD = 'lockId'
GATEWAY_ID_FIELD = 'gatewayId'
ELECTRIC_QUANTITY_FIELD = 'electricQuantity'
#
FINGERPRINT_FIELD = 'fingerprint'
GATEWAY_FIELD = 'gateway'
ID_CARD_FIELD = 'identityCard'
EKEY_FIELD = 'key'
PASSCODE_FIELD = 'keyboardPwd'
LOCK_FIELD = 'lock'
LOCK_RECORD_FIELD = 'lockRecord'
USER_FIELD = 'user'
WIRELESS_KEYPAD_FIELD = 'wirelessKeypad'
ADD_FIELD = 'add'
CHANGE_PERIOD_FIELD = 'changePeriod'
DELETE_FIELD = 'delete'
FREEZE_FIELD = 'freeze'
UNFREEZE_FIELD = 'unfreeze'
GET_FIELD = 'get'
LIST_FIELD = 'list'
LIST_BY_LOCK_FIELD = 'listByLock'
RENAME_FIELD = 'rename'
TRANSFER_FIELD = 'transfer'
UPGRADE_CHECK_FIELD = 'upgradeCheck'

#### singles
#  = 'fingerprint/clear'
#  = 'gateway/isInitSuccess'
LOCKS_PER_GATEWAY_RESOURCE = 'gateway/listLock'
#  = 'gateway/setUpgradeMode'
#  = 'gateway/uploadDetail'
#  = 'identityCard/clear'
#  = 'key/authorize'
#  = 'key/send'
#  = 'key/unauthorize'
#  = 'keyboardPwd/change'
LOCK_RESOURCE = 'lock/lock'
#  = 'lock/queryDate'
LOCK_STATE_RESOURCE = 'lock/queryOpenState'
#  = 'lock/queryStatus'
UNLOCK_RESOURCE = 'lock/unlock'
#  = 'lock/updateDate'
#  = 'lock/changeAdminKeyboardPwd'
#  = 'lock/changeDeletePwd'
#  = 'lock/configPassageMode'
#  = 'lock/deleteAllKey'
#  = 'lock/detail'
#  = 'lock/getKeyboardPwdVersion'
#  = 'lock/getPassageModeConfig'
#  = 'lock/initialize'
#  = 'lock/listKey'
#  = 'lock/listKeyboardPwd'
LOCK_ELECTRIC_QUANTITY_RESOURCE='lock/queryElectricQuantity'
#  = 'lock/resetKey'
#  = 'lock/resetKeyboardPwd'
#  = 'lock/setAutoLockTime'
#  = 'lock/updateElectricQuantity'
#  = 'lock/updateSpecialValue'
#  = 'lock/upgradeRecheck'
#  = 'lock/getDeviceInfo'
#  = 'lock/getNbPlatformIpAndPort'
#  = 'lock/registerNb'
#  = 'lockRecord/upload'
#  = 'user/getUid'
#  = 'user/register'
#  = 'user/resetPassword'


# OTHERS
LOCK_RECORDS_RESOURCE = 'lockRecord/list'
GOOD_HTTP_CODES = [200, 201, 202, 203]
GATEWAY_LIST_RESOURCE = 'gateway/list'
GATEWAY_LIST_URL = '{}/{}?clientId={}&accessToken={}&pageNo={}&pageSize={}&date={}'
LOCKS_PER_GATEWAY_URL = '{}/{}?clientId={}&accessToken={}&gatewayId={}&date={}'
LOCK_RECORDS_URL = '{}/{}?clientId={}&accessToken={}&lockId={}&pageNo={}&pageSize={}&startDate={}&endDate={}&date={}'
LOCK_QUERY_URL = '{}/{}?clientId={}&accessToken={}&lockId={}&date={}'